### ISSUE TITLE
Resolver questão campos encavalados em tela cheia

### ISSUE THREAD

**Issue by lcabralramos** [lunhg/vanessador#3]

**Comment by lunhg** [comment]
O problema dos formulários eram da classe escolhida pelo bootstrap. Verificando o seguinte [artigo](https://www.sitepoint.com/responsive-web-design-tips-bootstrap-css/) , deu pra ver que estou usando estilos de resoluções médias ( como por exemplo `.col-md-*` ao invés de `.col-xd-*`

**Comment by lunhg** [comment]
Consegui reproduzir com o simulador de dispositivos o problema reportado.

Retirando `.col-*-*` e outras classes do html, os formulários responderam melhor, bem como colocando uma tag `<meta name="viewport"> ` no `<head>`. 

A imagem abaixo é do corrigido.
![pnhjqrai.p6.weaved.com-.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59722495b4df3d001a6b8071/125516c66e82c728ace21e0d46f89a92299391a886a7af15ea4af5953f43233d2a0bae6632c9a138ad4d71040c1b5ca6535d5643fefb8f2cf3b13c778c5908edd16f5b27926b43f8eb9003ad43eb7edf10d8eff6df0ed2e22f27e1818e4a3e1e031f81f65f3ca49142da15.png)

Ainda não vou fechar isso pois preciso reproduzir isso nos formulários de cursos e agora estou ajustando o estilo que afetou outras coisas.

**Comment by lunhg** [comment]
Formulários tb parece ok
![bwnnmpts.p19.weaved.com-.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59722495b4df3d001a6b8071/125516c66e82c728ace21e0d46ea83942d8f93bd9ca7af12fd13e791285022776707ac263dc7af6aaf50740b0a0c0abe4b4a5a4dfbfb8b2da1e33b708d5a0eeed16d5d70956947feecd10da313f871d51bdaebe5c01982fa3737e58d854e3b1e051e81ff5b3da49a4ecc4abb.png)
