### ISSUE TITLE
Integração com paypal

### ISSUE THREAD

**Issue by marcoamarelo** [lunhg/vanessador#5]

**Comment by lunhg** [comment]
Criado um ponto de montagem que cria um `invoice` no paypal, funcionando como um boleto. Testado com mocha, mas ainda não verificado no app. Falta subir no github. Também falta criar pontos de montagem, um que verifica se este `invoice` foi pago ou não e outro que  envia o email.

    it "should GET /paypal/boleto/novo", ->
                new Promise (resolve, reject) ->
                        agent.get("/paypal/boleto/novo")
                                .query(first_name: "Nome")
                                .query(second_name: "Sobrenome")
                                .query(phone_country_code: "51")
                                .query(phone_national_number: "12345678")
                                .query(line: "Rua")
                                .query(city: "Cidade")
                                .query(state: "SP")
                                .query(postal_code: "1234567")
                                .query(country_code: "BR")
                                .query(value:'10.00')
                                .query(billing_info_email:'emaildetest@paypal.com')
                                .query(form:'lD26uE')
                                .expect 200

Retornou um JSON, do qual os valores mais importantes, para identificação do boleto, no vanessador:

    { id: 'INV2-ES9A-SVAT-D7V3-8UZ7',
      number: '0002',
      template_id: 'TEMP-3RN27355UC094144S',
      status: 'DRAFT',
      merchant_info: ... }

**Comment by lunhg** [comment]
Realizei testes com a api do paypal com o seguinte ciclo:

  - criar boleto (invoice)
- ver status do boleto
  - enviar solicitação ao paypal para envio de email do invoice para o usuário
  - enviar solicitação ao paypal para relembrar o invoice ao usuário
  - cancelar invoice

Enviei um vídeo p o slack mostrando o processo.

**Comment by lunhg** [comment]
Ciclo mais específico

    it "should GET /paypal/invoices/:id", ->
                new Promise (resolve, reject) ->
                        agent.get("/paypal/invoices/#{payment_id}")
                                .expect 200
                                .expect 'Content-Type', /json/
                                .expect (res) ->
                                        res.body.should.have.property 'status'
                                        res.body.status.should.equal 'DRAFT'
                                .then(resolve)
                                .catch(reject)

        it "should GET /paypal/invoices/:id/send", ->
                new Promise (resolve, reject) ->
                        setTimeout ->
                                agent.get("/paypal/invoices/#{payment_id}/send")
                                        .expect 200
                                        .expect (res) ->
                                                res.body.should.be.String()
                                        .then(resolve)
                                        .catch(reject)
                        , 1000

        it "should GET /paypal/invoices/:id a second time, with different status", ->
                new Promise (resolve, reject) ->
                        agent.get("/paypal/invoices/#{payment_id}")
                                .expect 200
                                .expect 'Content-Type', /json/
                                .expect (res) ->
                                        res.body.should.have.property 'status'
                                        res.body.status.should.equal 'SENT'
                                .then(resolve)
                                .catch(reject)

        it "should GET /paypal/invoices/:id/remind", ->
                new Promise (resolve, reject) ->
                        setTimeout ->
                                agent.get("/paypal/invoices/#{payment_id}/remind")
                                        .expect 200
                                        .expect (res) ->
                                                res.body.should.be.String()
                                        .then(resolve)
                                        .catch(reject)
                        , 1000
                        
        it "should GET /paypal/invoices/:id/cancel", ->
                new Promise (resolve, reject) ->
                        setTimeout ->
                                agent.get("/paypal/invoices/#{payment_id}/cancel")
                                        .expect 200
                                        .expect (res) ->
                                                res.body.should.be.String()
                                        .then(resolve)
                                        .catch(reject)
                        , 1000
                        
        it "should GET /paypal/invoices/:id a third time, with status canceled", ->
                new Promise (resolve, reject) ->
                        agent.get("/paypal/invoices/#{payment_id}")
                                .expect 200
                                .expect 'Content-Type', /json/
                                .expect (res) ->
                                        res.body.should.have.property 'status'
                                        res.body.status.should.equal 'CANCELLED'
                                .then(resolve)
                                .catch(reject)
